name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Install security tools
        run: |
          pip install bandit safety==2.3.5

      - name: Run Bandit scan
        run: |
          bandit -r app --exclude app/venv,app/__pycache__

      - name: Run Safety scan
        run: |
          cd app
          safety check -r requirements.txt

